lethain/staff-eng

- src/markdown/guides/overview-overview.md
> Fix  "Getting the title" item

- src/pages/about.js
Small typo and removed a reference to the currently 404'ing survey. A quick grep suggests this is the last reference to the survey.
> About page fixes

- src/markdown/stories/ras-kasa-williams.md
> Add story for Ras Kasa Williams

- README.md
- src/components/layout.js
- src/markdown/stories/keavy-mcminn.md
GitHub is properly cased with a capital H. :octocat:
Thanks for this great resource!
> GitHub is properly cased with a capital H

- src/markdown/guides/operating-at-staff.md
I think this word is meant to be `vet` as in to `vet a decision`.
> Minor typo

- src/markdown/stories/greg-wittel.md
Finally submitting my story.  Any feedback would be most welcome!
> Add story from Greg Wittel

- src/markdown/stories/john-zittlau.md
Cool project. I've been a Staff eng. for 5 years and a Principal Eng. for 3. I'm sharing thoughts from both levels.
> Adding John Zittlau's story

- src/markdown/guides/deciding-to-switch.md
- src/markdown/guides/finding-the-right-company.md
This PR is mostly for typos or any suggestions around the writing I have. I found a typo in a chapter other than the one I was supposed to review. Hope thats okay.
> Typos and corrections

- src/markdown/stories/dmitry-petrashko.md
Hi Will, 
as discussed over email, here are some updates that help bring story up to date.
Thank you,
Dmitry
> Updates on current role & how it differs from PTL

- src/markdown/guides/being-visible.md
This removes an extra blank, and fixes a typo.
> Fix typos in "Being visible"

- src/markdown/guides/does-the-staff-title-matter.md
I knew I had read the Archetypes section before.
But I wanted a link so i can check what _Solvers_ are.
> Cross-link from Does Title Matter -> Archetypes

- src/markdown/stories/aaron-suggs.md
Hi @lethain, I liked how the links section broke up Alex's story (#44). So I took a stab at adding my own. Cool?
This PR merges into #45.
> Add pull section of selected links

- src/markdown/stories/aaron-suggs.md
This replaces https://github.com/lethain/staff-eng/pull/41
> New PR for Aaron Sugg's story

- src/markdown/stories/aaron-suggs.md
It's a rule to only notice some typos after the story's published, right? :laughing:
> Fix minor typos in Aaron Suggs' story

- static/book.html
I think this was intended to read "will you" vs "you will"
> Swap word ordering

- src/components/header.js
In order to prepare for launching the podcast next week, I'm adding
a link to the header so folks can find the podcast from the main
website.
> Add link to podcast

- src/markdown/guides/create-space-for-others.md
- src/markdown/guides/present-to-executives.md
- src/markdown/guides/work-on-what-matters.md
I came across a few instances of what may be typos or grammar mistakes while reading through the first half of Staff Eng. Please take anything that you agree with!
> Fix typos and grammar

- src/markdown/guides/work-on-what-matters.md
> Fix small typo in work-on-what-matters.md

- src/markdown/stories/mikhail-chernykh.md
Hi @lethain, thanks for driving the StaffEng.com website, I particularly like the stories part. 
I would like to share my a story of being a Staff Engineer at Indeed. Hope it will give some visibility to our organization. 
Looking forward to hearing from you!
> docs: Add Mikhail Chernykh's story

- src/markdown/stories/rebecca-panja.md
Hi @lethain, StaffEng has been an incredible learning resource for me and I'd love to contribute my story to it :) 
Let me know if you have any feedback or edits in mind, thanks!
> Add Rebecca Panja's story

- static/book.html
Reading the description, I saw what I believe to be a typo, I'm offering the PR as a fix.
> Fix typo in book.html

- src/markdown/stories/adam-bender.md
Hey all, I really appreciate this project! I wish it had existed when I first hit Staff myself.
Hope my PR meets the bar for inclusion, feel free to let me know if anything needs to change.
> Adding a new story for adambender

- src/markdown/stories/dmitry-petrashko.md
I came across some grammar mistakes as I was reading some stories in Staff Eng. Feel free to accept the ones that you agree with; if you have feedback on some of the proposed changes, I'd be more than happy to roll them into this PR!
> Fix minor grammar mistakes
